import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";
import Game from "../components/game";
import Footer from "../components/footer";

const Home: NextPage = () => {
  return (
    <div className="h-screen flex flex-col justify-between items-center px-24 py-12 bg-gray-50">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Game />
      <Footer />
    </div>
  );
};

export default Home;
