import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import Play from "../components/play";
import Author from "../components/author";

const Home: NextPage = () => {
  return (
    <div className="h-screen flex flex-col justify-between content-center px-24 py-12 bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Play />
      <Author />
    </div>
  );
};

export default Home;
